### ISSUE TITLE
Book selection

### ISSUE THREAD

**Issue by MarioGuCBMR** [science-collective/scoping-review#20]
Following the TODO added by @hchats in the protocol, maybe we should add books. A maximum of 4 books should be added after reaching a common consensus among the collaborators. 

In this issue I suggest that we discuss of the best strategies to look for books (if they differ to those used for other type of data) so that they can be added in the protocol accordingly.

**Comment by danielibsen** [comment]
That is very interesting @MarioGuCBMR. I had not expected that many books. But cool that we found some. In the protocol, I set the limit to be 4 books, because reading a lot of book could potentially be very time consuming. 

Where did you put the list of books? Then we can have a look at it before meeting next time where we could talk about them.

Re the noise, I think we should be careful not making the search to narrow given that we want to map out the evidence on the topic.

**Comment by hchats** [comment]
Great idea on the 4 book limit @MarioGuCBMR @danielibsen! I did a quick search of Google Books and there were 20+ pages of results. However, as you say @MarioGuCBMR, there is considerable noise. I got the same when testing the journal article search in SCOPUS. To some extent, I think that's just part of the deal and something we will have to deal with during screening.

**Comment by danielibsen** [comment]
Although we did not agree on books, I found this one and I am currently reading it. Really great and a lot of examples. 

https://www.amazon.com/Reinventing-Discovery-New-Networked-Science/dp/0691160198

I searched for open science on Google Books and among the top hits came these 4 that were most relevant:

*A journey into open science and research in psychology*
https://www.google.dk/books/edition/A_Journey_into_Open_Science_and_Research/REY3EAAAQBAJ?hl=da&gbpv=0

*Implementing reproducible research*
https://www.google.dk/books/edition/Implementing_Reproducible_Research/xEQPEAAAQBAJ?hl=da&gbpv=0

*Open science - sharing knowledge in the global century*
https://www.google.dk/books/edition/Open_Science/N0gUsSPHlZUC?hl=da&gbpv=0

*Open science by design*
https://www.google.dk/books/edition/Open_Science_by_Design/_B1sDwAAQBAJ?hl=da&gbpv=0

I think this part will be hard to reproduce (paradoxically?) But having searched for books, picked what we sought the most relevant and recent will definitely be better than nothing. I will give us a lot of inspiration and some broader knowledge about the topic. 

And how should we do with the reading? Each person reads a book and gives a summary and highlight to the others?

**Comment by lwjohnst86** [comment]
Books are included in Open Alex, so our `records.csv` data file also has books.
