### ISSUE TITLE
Ideas for strategy for searching web, literature, and any other resource for any given topic area

### ISSUE THREAD

**Issue by lwjohnst86** [science-collective/scoping-review#3]
Linked to ideas here: https://github.com/science-collective/admin/issues/5

Specifically comments:

- https://github.com/science-collective/admin/issues/5#issuecomment-1014401919
- https://github.com/science-collective/admin/issues/5#issuecomment-1014749869
- https://github.com/science-collective/admin/issues/5#issuecomment-1014875357
- https://github.com/science-collective/admin/issues/5#issuecomment-1040667323

What I've gotten from the discussion so far is to:

1. Test out a few strategies (get some insight from the librarian)
2. There are so many topics within this area, maybe focus down on a few. I suggest we focus first on open collaboration connected to open science practices, since that's what we're doing right now :stuck_out_tongue_closed_eyes: 
3. Brainstorm our specific aim and questions to help focus our search
3. Decide and agree on some strategies and the overall protocol. Here I'd suggest we write out a draft protocol that specifically focuses on how we'd go about doing it as a team

**Comment by MarioGuCBMR** [comment]
I am going to start with point 4: how can we work together in this as a team and specifically in github? This is linked to the request about storing references (https://github.com/science-collective/scoping-review/pull/2), since depending on how we do that, it will determine our teamwork.

For me there are two elements that should be present:

1) a main document that keeps being updated with the references (of course!)
2) a (maybe separate) log of the references, the databases and the search terms.

For me the log is important to avoid redundancy. By knowing what Hannah has done, for example, allows me to maybe search with the same terms that she has used, but in another database, or use other synonyms in the same database. I think the log should be a separate document from the main one, which should be the final product to use in R to obtain all references in the format we desire. I will add more thoughts on the format in the request (link is above.) 

However, focusing on the log, it could have the following formats:

1) Issue format: Every time someone is working on looking for references, they comment on an issue with the "literature" label and they write the database and the terms used and the references obtained. For example: 

Term(s): Open collaboration
Databases: SCOPUS.
References: [add here]

I think this is great to see who is working with what that day, so you can organize yourself and do something else. The main issue is that you cannot parse all the terms that we can come up with be reading comments. For that reason, this info could be supported by:

2) A table terms X databases: a simple database where we can go and check what has been done already. We go and check: "Open Collaboration" has been searched in SCOPUS. Then, it is time to try another database. Of course, this can be bothersome if you start combining terms, but we can come up ways of sorting that out. 

All in all, the loop I propose, would be the following:

1) Check the termsXdatabases table. Choose what are you going to use.
2) Go through literature and save references. 
3) Comment on the "literature" issue the results of your search (plus comments about what you have found, if necessary)
4) Report the references in the final format in the main document.

Let me know your thoughts, this was a bit improvised, but I feel like some kind of document is needed so that in a glance we can avoid redundancy and we know how far from our objective we are.
