### ISSUE TITLE
Complete functions for extracting from MedRxiv

### ISSUE THREAD

**Issue by lwjohnst86** [science-collective/scoping-review#42]
Write functions that will extract from the source and download to the repository. To finish this issue, we don't need to download and save the data from the source, we only need the code.

Code should be placed in: `R/medrxiv-search.R`

**Comment by MarioGuCBMR** [comment]
Medrxiv code is giving me headaches. I cannot replicate the searches of the website with the code. 
I tried running the code with just "open collaboration" as search term, but only obtained one result.

However, when I search in medrxiv I found 7000~ results: 
https://www.medrxiv.org/search/open%252Bcollaboration%20jcode%3Amedrxiv%20limit_from%3A2017-01-01%20limit_to%3A2023-04-21%20numresults%3A10%20sort%3Arelevance-rank%20format_result%3Astandard

The reason is that mx_search has a totally independent way of running the searches. I might need a bit of help with this!

**Comment by MarioGuCBMR** [comment]
Update: last week they added this get started page that might be useful: https://docs.ropensci.org/medrxivr/articles/medrxivr.html

**Comment by MarioGuCBMR** [comment]
The issue @danielibsen found with mx_snapshot is still there, but using the parent function locally (mx_api_content), seems to solve this. It takes a while though

**Comment by lwjohnst86** [comment]
This was finished a while ago.
